"""Build the "things I've shipped" section from assets/projects.json.

Each featured project becomes a small animated terminal card (dark + light) in
assets/projects/, and the README block between the PROJECTS markers is rewritten:
a two-column grid of cards (each linking to its first link) followed by a compact
table of the remaining projects.

    python scripts/projects.py
"""
import json
import textwrap
from pathlib import Path
from xml.sax.saxutils import escape

from style import CHAR, THEMES, num, odometer, svg_open, text

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets/projects.json"
OUT = ROOT / "assets/projects"
README = ROOT / "README.md"
START, END = "<!-- PROJECTS:START", "<!-- PROJECTS:END -->"
W, H = 560, 240
STAGGER = 0.18                 # seconds between cards, so the grid lights up in reading order


def status(links):
    """Where the project lives, from its links: the strongest one wins."""
    labels = {link["label"] for link in links}
    for label, words in (("Demo", "LIVE DEMO"), ("Live", "LIVE SITE"), ("PyPI", "ON PYPI"), ("Model", "ON HUGGING FACE")):
        if label in labels:
            return words
    return "SOURCE ON GITHUB"


def card(p, i, t):
    delay = STAGGER * i
    o = [svg_open(W, H, f'{p["name"]}: {p["blurb"]}', t),
         f'<rect width="{W}" height="{H}" rx="14" fill="{t["bg"]}"/>',
         f'<rect x="6" y="6" width="{W - 12}" height="{H - 12}" rx="11" fill="{t["panel"]}" stroke="{t["line"]}"/>']
    for k, c in enumerate(("#FF5F57", "#FEBC2E", "#28C840")):
        o.append(f'<circle cx="{26 + 16 * k}" cy="27" r="5" fill="{c}"/>')
    o.append(text(W / 2, 31, f"~/shipped/{p['slug']}", 11, t["muted"], "middle", extra=' letter-spacing=".3"'))
    o.append(text(W - 22, 31, f"#{i + 1:02d}", 11, t["muted"], "end"))
    o.append(f'<path d="M6 48H{W - 6}" stroke="{t["line"]}"/>')
    # load bar racing along the title bar divider
    o.append(f'<rect x="6" y="47" width="{W - 12}" height="2" fill="{t["chrome"]}" opacity=".7">'
             f'<animate attributeName="width" values="0;0;{W - 12}" keyTimes="0;{delay / (delay + 1):.3f};1" '
             f'dur="{delay + 1:.2f}s" calcMode="spline" keySplines="0 0 1 1;0.4 0 0.2 1" fill="freeze"/></rect>')

    # category pill
    tag_w = len(p["tag"]) * 10 * (CHAR + 0.08) + 20
    o.append(f'<rect x="22" y="62" width="{num(tag_w)}" height="20" rx="10" fill="{t["chrome"]}" fill-opacity=".12" '
             f'stroke="{t["chrome"]}" stroke-opacity=".45"/>')
    o.append(text(32, 76, p["tag"], 10, t["chrome"], weight=700, extra=' letter-spacing=".8"'))

    # name and blurb type themselves out once the load bar lands
    reveal = delay + 0.5
    o.append(f'<clipPath id="type"><rect x="16" y="90" width="{W - 32}" height="80">'
             f'<animate attributeName="width" values="0;0;{W - 32}" keyTimes="0;{reveal / (reveal + .9):.3f};1" '
             f'dur="{reveal + .9:.2f}s" fill="freeze"/></rect></clipPath><g clip-path="url(#type)">')
    o.append(text(22, 114, p["name"], 21, t["text"], weight=700))
    for k, line in enumerate(textwrap.wrap(p["blurb"], int((W - 44) / (13 * CHAR)))[:2]):
        o.append(text(22, 138 + 18 * k, line, 13, t["muted"]))
    o.append("</g>")

    # stack chips, and the headline number (digits roll in) on the right
    metric = p.get("metric")
    right = W - 22
    if metric:
        size = 24
        value_w = len(metric["value"]) * size * CHAR
        o.append(odometer(right - value_w, 196, metric["value"], size, t["text"], "metric", delay + 0.3))
        o.append(text(right - value_w - 8, 196, metric["label"], 10, t["muted"], "end"))
        right -= value_w + 8 + len(metric["label"]) * 10 * CHAR + 16
    cx = 22
    for chip in p["stack"]:
        w = len(chip) * 11 * CHAR + 16
        if cx + w > right:
            break
        o.append(f'<rect x="{num(cx)}" y="178" width="{num(w)}" height="22" rx="4" fill="{t["panel2"]}" stroke="{t["line"]}"/>')
        o.append(text(cx + 8, 193, chip, 11, t["text"]))
        cx += w + 8

    # footer: where it lives (status dot pulses) and which links sit under the card
    o.append(f'<path d="M22 208H{W - 22}" stroke="{t["line"]}" stroke-dasharray="1 5"/>')
    o.append(f'<circle cx="26" cy="222" r="3.5" fill="{t["accent"]}"><animate attributeName="opacity" values="1;.3;1" '
             f'dur="1.6s" begin="{delay:.2f}s" repeatCount="indefinite"/></circle>')
    o.append(text(36, 226, status(p["links"]), 10, t["accent"], weight=700, extra=' letter-spacing=".6"'))
    o.append(text(W - 22, 226, " · ".join(link["label"].upper() for link in p["links"]), 10, t["muted"], "end"))
    o.append("</svg>")
    return "".join(o)


def links_md(links):
    return " · ".join(f'<a href="{escape(link["url"])}">{escape(link["label"])}</a>' for link in links)


def readme_block(data):
    o = [f"{START} - generated by scripts/projects.py from assets/projects.json; edit that, not this -->",
         "<table>"]
    featured = data["featured"]
    for row in range(0, len(featured), 2):
        o.append("<tr>")
        for p in featured[row:row + 2]:
            src = f"assets/projects/{p['slug']}"
            alt = escape(f"{p['name']}: {p['blurb']}", {'"': "&quot;"})
            o += ['<td width="50%" align="center" valign="top">',
                  f'<a href="{escape(p["links"][0]["url"])}"><picture>',
                  f'  <source media="(prefers-color-scheme: dark)"  srcset="{src}-dark.svg">',
                  f'  <source media="(prefers-color-scheme: light)" srcset="{src}-light.svg">',
                  f'  <img src="{src}-dark.svg" width="100%" alt="{alt}">',
                  "</picture></a>",
                  f"<sub>{links_md(p['links'])}</sub>",
                  "</td>"]
        o.append("</tr>")
    o.append("</table>")
    if data.get("more"):
        o += ["", '<p align="center"><b>also shipped</b></p>', "",
              "| Project | What it is | Links |", "|:--|:--|:--|"]
        for p in data["more"]:
            links = " · ".join(f"[{link['label']}]({link['url']})" for link in p["links"])
            o.append(f"| {p['icon']} **{p['name']}** | {p['blurb']} | {links} |")
    o += ["", END]                                     # a blank line ends the table before the marker
    return "\n".join(o)


def main():
    data = json.loads(DATA.read_text())
    OUT.mkdir(exist_ok=True)
    for i, p in enumerate(data["featured"]):
        for name, theme in THEMES.items():
            (OUT / f"{p['slug']}-{name}.svg").write_text(card(p, i, theme))
    readme = README.read_text()
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        README.write_text(head + readme_block(data) + rest.split(END, 1)[1])
    else:
        print(f"README has no {START} ... {END} block; cards written, README left alone")
    print(f"{len(data['featured'])} cards -> {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
